--Creates a breakdown of the size of every collection & how many are off shelf
select

count (case when itemcall.call_number_norm between '000' and '099.999' then 1 end) as "000-099 0",
count (case when itemcall.call_number_norm between '100' and '199.999' then 1 end) as "100-199 1",
count (case when itemcall.call_number_norm between '200' and '299.999' then 1 end) as "200-299 2",
count (case when itemcall.call_number_norm between '300' and '399.999' then 1 end) as "300-399 3",
count (case when itemcall.call_number_norm between '400' and '499.999' then 1 end) as "400-499 4",
count (case when itemcall.call_number_norm between '500' and '599.999' then 1 end) as "500-599 5",
count (case when itemcall.call_number_norm between '600' and '699.999' then 1 end) as "600-699 6",
count (case when itemcall.call_number_norm between '700' and '799.999' then 1 end) as "700-799 7",
count (case when itemcall.call_number_norm between '800' and '899.999' then 1 end) as "800-899 8",
count (case when itemcall.call_number_norm between '900' and '999.999' then 1 end) as "900-999 9",
Count (case when itemcall.call_number_norm like 'r%' then 1 end) as " Adult REF 10",

count (case when itemcall.call_number_norm like 'expre%' then 1 end) as "Express 11" ,
count (case when itemcall.call_number_norm like 'fict%' then 1 end) as "Fiction 12",
count (case when itemcall.call_number_norm like 'myst%' then 1 end) as "Mystery 13",
count (case when itemcall.call_number_norm like 'scifi%' then 1 end) as "SCIFI 14",
count (case when itemcall.call_number_norm like 'grap%' then 1 end) as "Graphic Novel 15",
count (case when itemcall.call_number_norm like 'lt%' then 1 end) as "LT 16",
count (case when itemcall.call_number_norm like 'pbk%'  then 1 end) as "Paperbacks 17",
count (case when (itemcall.call_number_norm like 'jpn%' or itemcall.call_number_norm like 'japan%') then 1 end) as "Japanese 18",
count (case when itemcall.call_number_norm like 'spa%' then 1 end) as "Spanish 19",
Count (case when itemcall.call_number_norm like 'lang%' then 1 end) as "Language Learning 20",

count (case when (itemcall.call_number_norm like 'dvd%' or itemcall.call_number_norm like 'blu%')  then 1 end) as "DVDs 21",
count (case when itemcall.call_number_norm like 'comp disc%'  and item.itype_code_num = '2'  then 1 end) as "Music CDs 22",
count (case when itemcall.call_number_norm like 'comp disc%' and item.itype_code_num = '22' then 1 end) as "AudioBook 23",

count (case when itemcall.call_number_norm like 'ya%' then 1 end) as "YA 24",
count (case when item.itype_code_num = '9' and itemcall.call_number_norm not like 'j %' then 1 end) as "Magazines (ADULT AND YA) 25",
count (case when itemcall.call_number_norm like 'music s%' then 1 end) as "Music score 26",

count (case when itemcall.call_number_norm like 'j fict%' then 1 end) as "J FICTION 27",
count (case when itemcall.call_number_norm like 'j graph%' then 1 end) as "J GRAPHIC NOVEL 28",
count (case when itemcall.call_number_norm like 'e%' AND itemcall.call_number_norm not like 'e boardb%' AND itemcall.call_number_norm not like 'e comp disc%' then 1 end) as "e Books 29",
count (case when itemcall.call_number_norm like 'e board%' then 1 end) as "e BoardBooks 30",
count (case when itemcall.call_number_norm like 'j paper%' then 1 end) as "J PAPERBACK 31",
count (case when itemcall.call_number_norm like 'j b%' then 1 end) as "J BIOGRAPHY 32",
count (case when itemcall.call_number_norm like 'j pic%' then 1 end) as "J PIC 33",
count (case when itemcall.call_number_norm like 'j-%' then 1 end) as "J-1, J-2, J-3 34", --added 2/2/24

count (case when itemcall.call_number_norm between 'j 001' and 'j 099.999' then 1 end) as "J 001-099 35",
count (case when itemcall.call_number_norm between 'j 100' and 'j 199.999' then 1 end) as "J 100-199 36",
count (case when itemcall.call_number_norm between 'j 200' and 'j 299.999' then 1 end) as "J 200-299 37",
count (case when itemcall.call_number_norm between 'j 300' and 'j 399.999' then 1 end) as "J 300-399 38",
count (case when itemcall.call_number_norm between 'j 400' and 'j 499.999' then 1 end) as "J 400-499 39",
count (case when itemcall.call_number_norm between 'j 500' and 'j 599.999' then 1 end) as "J 500-599 40",
count (case when itemcall.call_number_norm between 'j 600' and 'j 699.999' then 1 end) as "J 600-699 41",
count (case when itemcall.call_number_norm between 'j 700' and 'j 799.999' then 1 end) as "J 700-799 42",
count (case when itemcall.call_number_norm between 'j 800' and 'j 899.999' then 1 end) as "J 800-899 43",
count (case when itemcall.call_number_norm between 'j 900' and 'j 999.999' then 1 end) as "J 900-999 44",

Count (case when itemcall.call_number_norm like 'j jpn%' then 1 end) as " J Japanese 45",
Count (case when itemcall.call_number_norm like 'j spa%' then 1 end) as " J Spanish 46",
Count (case when itemcall.call_number_norm like 'j chi%' then 1 end) as " J Chinese 47",
Count (case when itemcall.call_number_norm like 'j fre%' then 1 end) as " J FRE 48",
Count (case when (itemcall.call_number_norm like 'j dvd%' or itemcall.call_number_norm like 'j blu%') then 1 end) as " J DVD 49",

Count (case when itemcall.call_number_norm like 'j comp%' and item.itype_code_num = '3' then 1 end) as " J Music CD 50",
Count (case when itemcall.call_number_norm like 'j comp%' and item.itype_code_num = '23' then 1 end) as " J AudioBook 51",
Count (case when itemcall.call_number_norm like 'e comp%' then 1 end) as "E COMP DISC 52",
Count (case when itemcall.call_number_norm like 'j lang%' then 1 end) as "Language Learning 53",
Count (case when itemcall.call_number_norm like 'j maga%' then 1 end) as "J Magazine 54",
Count (case when itemcall.call_number_norm like 'j ref%'  then 1 end) as " J REF 55",
count (case when item.location_code like 'gb%' then 1 end) as "All byram itemcall. 56",


count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between '000' and '099.999' then 1 end) as "000-099 57",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between '100' and '199.999' then 1 end) as "100-199 58",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between '200' and '299.999' then 1 end) as "200-299 59",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between '300' and '399.999' then 1 end) as "300-399 60",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between '400' and '499.999' then 1 end) as "400-499 61",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between '500' and '599.999' then 1 end) as "500-599 62",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between '600' and '699.999' then 1 end) as "600-699 63",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between '700' and '799.999' then 1 end) as "700-799 64",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between '800' and '899.999' then 1 end) as "800-899 65",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between '900' and '999.999' then 1 end) as "900-999 66",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'r%' then 1 end) as " Adult REF 67",

count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'expre%' then 1 end) as "Express 68",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'fict%' then 1 end) as "Fiction 69",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'myst%' then 1 end) as "Mystery 70",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'scifi%' then 1 end) as "SCIFI 71",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'grap%' then 1 end) as "Graphic Novel 72",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'lt%' then 1 end) as "LT 73",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'pbk%'  then 1 end) as "Paperbacks 74",
count (case when cout.loanrule_code_num > '0' and (itemcall.call_number_norm like 'jpn%' or itemcall.call_number_norm like 'japan%') then 1 end) as "Japanese 75",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'spa%' then 1 end) as "Spanish 76",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'lang%' then 1 end) as "Language Learning 77",

count (case when cout.loanrule_code_num > '0' and (itemcall.call_number_norm like 'dvd%' or itemcall.call_number_norm like 'blu%')  then 1 end) as "DVDs 78",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'comp disc%'  and item.itype_code_num = '2'  then 1 end) as "Music CDs 79",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'comp disc%' and item.itype_code_num = '22' then 1 end) as "AudioBook 80",

count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'ya%' then 1 end) as "YA 81",
count (case when cout.loanrule_code_num > '0' and item.itype_code_num = '9' and itemcall.call_number_norm not like 'j %' then 1 end) as "Magazines (ADULT AND YA) 82",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'music s%' then 1 end) as "Music score 83",

count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'j fict%' then 1 end) as "J FICTION 84",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'j graph%' then 1 end) as "J GRAPHIC NOVEL 85",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'e%' AND itemcall.call_number_norm not like 'e boardb%' AND call.index_entry not like 'e comp disc%' then 1 end) as "e Books 86",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'e board%' then 1 end) as "e BoardBooks 87",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'j paper%' then 1 end) as "J PAPERBACK 88",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'j b%' then 1 end) as "J BIOGRAPHY 89",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'j pic%' then 1 end) as "J PIC 90",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'j-%' then 1 end) as "J-1, J-2, J-3 91", --added 2/2/24

count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between 'j 001' and 'j 099.999' then 1 end) as "J 001-099 92",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between 'j 100' and 'j 199.999' then 1 end) as "J 100-199 93",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between 'j 200' and 'j 299.999' then 1 end) as "J 200-299 94",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between 'j 300' and 'j 399.9999' then 1 end) as "J 300-399 95",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between 'j 400' and 'j 499.999' then 1 end) as "J 400-499 96",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between 'j 500' and 'j 599.9999' then 1 end) as "J 500-599 97",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between 'j 600' and 'j 699.9999' then 1 end) as "J 600-699 98",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between 'j 700' and 'j 799.9999' then 1 end) as "J 700-799 99",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between 'j 800' and 'j 899.9999' then 1 end) as "J 800-899 100",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm between 'j 900' and 'j 999.9999' then 1 end) as "J 900-999 101",

count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'j jpn%' then 1 end) as " J Japanese 102",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'j spa%' then 1 end) as " J Spanish 103",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'j chi%' then 1 end) as " J Chinese 104",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'j fre%' then 1 end) as " J FRE 105",
count (case when cout.loanrule_code_num > '0' and (itemcall.call_number_norm like 'j dvd%' or itemcall.call_number_norm like 'j blu%') then 1 end) as " J DVD 106",

count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'j comp%' and item.itype_code_num = '3' then 1 end) as " J Music CD 107",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'j comp%' and item.itype_code_num = '23' then 1 end) as " J AudioBook 108",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'e comp%' then 1 end) as "E COMP DISC 109",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'j lang%' then 1 end) as "Language Learning 110",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'j maga%' then 1 end) as "J Magazine 111",
count (case when cout.loanrule_code_num > '0' and itemcall.call_number_norm like 'j ref%'  then 1 end) as " J REF 112",
count (case when cout.loanrule_code_num > '0' and item.location_code like 'gb%' then 1 end) as "All byram itemcall. 113",
count (case when item.record_creation_date_gmt > (now() - interval '6 months') and item.itype_code_num = '0'  then 1 end) as "new books 114",
count (case when cout.loanrule_code_num > '0' and item.record_creation_date_gmt > (now() - interval '6 months') and item.itype_code_num = '0'   then 1 end) as "new books c/out 115",
count (case when item.record_creation_date_gmt > (now() - interval '12 months') and (itemcall.call_number_norm between'j 000' and 'j 999.9999' or itemcall.call_number_norm like 'j b%')  then 1 end) as "New JUV Non-Fiction Books 116",
count (case when item.record_creation_date_gmt > (now() - interval '12 months') and (itemcall.call_number_norm between 'j 000' and 'j 999.9999' or itemcall.call_number_norm like 'j b%') and cout.loanrule_code_num > '0' then 1 end) as "New JUV Non-Fiction Books C/out 117",
count (case when item.record_creation_date_gmt > (now() - interval '12 months') and (itemcall.call_number_norm like 'j pbk' or itemcall.call_number_norm like 'j graphic%' or itemcall.call_number_norm like 'j fic%') then 1 end) as "New J Fiction Books 118",
count (case when item.record_creation_date_gmt > (now() - interval '12 months') and (itemcall.call_number_norm like 'j pbk' or itemcall.call_number_norm like 'j graphic%' or itemcall.call_number_norm like 'j fic%') and cout.loanrule_code_num > '0' then 1 end) as "New J Fiction Books C/out 119",
count (case when item.record_creation_date_gmt > (now() - interval '12 months') and itemcall.call_number_norm like 'e%' then 1 end) as "New E Books 120",
count (case when item.record_creation_date_gmt > (now() - interval '12 months') and itemcall.call_number_norm like 'e%' and cout.loanrule_code_num <> '0'  then 1 end) as "New E Books C/out 121",

count (case when itemcall.call_number_norm between '000' and '099.999' and item.item_status_code <> '-' then 1 end) as "000-099 122",
count (case when itemcall.call_number_norm between '100' and '199.999' and item.item_status_code <> '-' then 1 end) as "100-199 123",
count (case when itemcall.call_number_norm between '200' and '299.999' and item.item_status_code <> '-' then 1 end) as "200-299 124",
count (case when itemcall.call_number_norm between '300' and '399.999' and item.item_status_code <> '-' then 1 end) as "300-399 125",
count (case when itemcall.call_number_norm between '400' and '499.999' and item.item_status_code <> '-' then 1 end) as "400-499 126",
count (case when itemcall.call_number_norm between '500' and '599.999' and item.item_status_code <> '-' then 1 end) as "500-599 127",
count (case when itemcall.call_number_norm between '600' and '699.999' and item.item_status_code <> '-' then 1 end) as "600-699 128",
count (case when itemcall.call_number_norm between '700' and '799.999' and item.item_status_code <> '-' then 1 end) as "700-799 129",
count (case when itemcall.call_number_norm between '800' and '899.999' and item.item_status_code <> '-' then 1 end) as "800-899 130",
count (case when itemcall.call_number_norm between '900' and '999.999' and item.item_status_code <> '-' then 1 end) as "900-999 131",
Count (case when itemcall.call_number_norm like 'r%' and item.item_status_code <> '-' and item.item_status_code <> 'o' then 1 end) as " Adult REF 132",

count (case when itemcall.call_number_norm like 'expre%' and item.item_status_code <> '-' then 1 end) as "Express 133",
count (case when itemcall.call_number_norm like 'fict%' and item.item_status_code <> '-' then 1 end) as "Fiction 134",
count (case when itemcall.call_number_norm like 'myst%' and item.item_status_code <> '-' then 1 end) as "Mystery 135",
count (case when itemcall.call_number_norm like 'scifi%' and item.item_status_code <> '-' then 1 end) as "SCIFI 136",
count (case when itemcall.call_number_norm like 'grap%' and item.item_status_code <> '-' then 1 end) as "Graphic Novel 137",
count (case when itemcall.call_number_norm like 'lt%' and item.item_status_code <> '-' then 1 end) as "LT 138",
count (case when itemcall.call_number_norm like 'pbk%'  and item.item_status_code <> '-' then 1 end) as "Paperbacks 139",
count (case when (itemcall.call_number_norm like 'jpn%' or itemcall.call_number_norm like 'japan%') and item.item_status_code <> '-' then 1 end) as "Japanese 140",
count (case when itemcall.call_number_norm like 'spa%' and item.item_status_code <> '-' then 1 end) as "Spanish 141",
Count (case when itemcall.call_number_norm like 'lang%' and item.item_status_code <> '-' then 1 end) as "Language Learning 142",

count (case when (itemcall.call_number_norm like 'dvd%' or itemcall.call_number_norm like 'blu%')  and item.item_status_code <> '-' then 1 end) as "DVDs 143",
count (case when itemcall.call_number_norm like 'comp disc%'  and item.itype_code_num = '2'  and item.item_status_code <> '-' then 1 end) as "Music CDs 144",
count (case when itemcall.call_number_norm like 'comp disc%' and item.itype_code_num = '22' and item.item_status_code <> '-' then 1 end) as "AudioBook 145",

count (case when itemcall.call_number_norm like 'ya%' and item.item_status_code <> '-' then 1 end) as "YA 146",
count (case when item.itype_code_num = '9' and itemcall.call_number_norm not like 'j %' and item.item_status_code <> '-' then 1 end) as "Magazines (ADULT AND YA) 147",
count (case when itemcall.call_number_norm like 'music s%' and item.item_status_code <> '-' then 1 end) as "Music score 148",

count (case when itemcall.call_number_norm like 'j fict%' and item.item_status_code <> '-' then 1 end) as "J FICTION 149",
count (case when itemcall.call_number_norm like 'j graph%' and item.item_status_code <> '-' then 1 end) as "J GRAPHIC NOVEL 150",
count (case when itemcall.call_number_norm like 'e%' AND itemcall.call_number_norm not like 'e boardb%' AND call.index_entry not like 'e comp disc%' and item.item_status_code <> '-' then 1 end) as "e Books 151",
count (case when itemcall.call_number_norm like 'e board%' and item.item_status_code <> '-' then 1 end) as "e BoardBooks 152",
count (case when itemcall.call_number_norm like 'j paper%' and item.item_status_code <> '-' then 1 end) as "J PAPERBACK 153",
count (case when itemcall.call_number_norm like 'j b%' and item.item_status_code <> '-' then 1 end) as "J BIOGRAPHY 154",
count (case when itemcall.call_number_norm like 'j pic%' and item.item_status_code <> '-' then 1 end) as "J PIC 155",
count (case when itemcall.call_number_norm like 'j-%' and item.item_status_code <> '-' then 1 end) as "J-1, J-2, J-3 156", --added 2/2/24

count (case when itemcall.call_number_norm between 'j 001' and 'j 099.9999' and item.item_status_code <> '-' then 1 end) as "J 001-099 157",
count (case when itemcall.call_number_norm between 'j 100' and 'j 199.9999' and item.item_status_code <> '-' then 1 end) as "J 100-199 158",
count (case when itemcall.call_number_norm between 'j 200' and 'j 299.9999' and item.item_status_code <> '-' then 1 end) as "J 200-299 159",
count (case when itemcall.call_number_norm between 'j 300' and 'j 399.9999' and item.item_status_code <> '-' then 1 end) as "J 300-399 160",
count (case when itemcall.call_number_norm between 'j 400' and 'j 499.9999' and item.item_status_code <> '-' then 1 end) as "J 400-499 161",
count (case when itemcall.call_number_norm between 'j 500' and 'j 599.9999' and item.item_status_code <> '-' then 1 end) as "J 500-599 162",
count (case when itemcall.call_number_norm between 'j 600' and 'j 699.9999' and item.item_status_code <> '-' then 1 end) as "J 600-699 163",
count (case when itemcall.call_number_norm between 'j 700' and 'j 799.9999' and item.item_status_code <> '-' then 1 end) as "J 700-799 164",
count (case when itemcall.call_number_norm between 'j 800' and 'j 899.9999' and item.item_status_code <> '-' then 1 end) as "J 800-899 165",
count (case when itemcall.call_number_norm between 'j 900' and 'j 999.9999' and item.item_status_code <> '-' then 1 end) as "J 900-999 166",

Count (case when itemcall.call_number_norm like 'j jpn%' and item.item_status_code <> '-' then 1 end) as " J Japanese 167",
Count (case when itemcall.call_number_norm like 'j spa%' and item.item_status_code <> '-' then 1 end) as " J Spanish 168",
Count (case when itemcall.call_number_norm like 'j chi%' and item.item_status_code <> '-' then 1 end) as " J Chinese 169",
Count (case when itemcall.call_number_norm like 'j fre%' and item.item_status_code <> '-' then 1 end) as " J FRE 170",
Count (case when (itemcall.call_number_norm like 'j dvd%' or itemcall.call_number_norm like 'j blu%') and item.item_status_code <> '-' then 1 end) as " J DVD 171",

Count (case when itemcall.call_number_norm like 'j comp%' and item.itype_code_num = '3' and item.item_status_code <> '-' then 1 end) as " J Music CD 172",
Count (case when itemcall.call_number_norm like 'j comp%' and item.itype_code_num = '23' and item.item_status_code <> '-' then 1 end) as " J AudioBook 173",
Count (case when itemcall.call_number_norm like 'e comp%' and item.item_status_code <> '-' then 1 end) as "E COMP DISC 174",
Count (case when itemcall.call_number_norm like 'j lang%' and item.item_status_code <> '-' then 1 end) as "Language Learning 175",
Count (case when itemcall.call_number_norm like 'j maga%' and item.item_status_code <> '-' then 1 end) as "J Magazine 176",
Count (case when itemcall.call_number_norm like 'j ref%'  and item.item_status_code <> '-' and item.item_status_code <> 'o' then 1 end) as " J REF 177",
count (case when item.location_code like 'gb%' and item.item_status_code <> '-' then 1 end) as "All byram itemcall 178",

count (case when item.record_creation_date_gmt > (now() - interval '6 months') and item.itype_code_num = '0' and item.item_status_code <> '-' then 1 end) as "new books Other status 179",
count (case when item.record_creation_date_gmt > (now() - interval '12 months') and (itemcall.call_number_norm between 'j 000' and 'j 999.9999' or itemcall.call_number_norm like 'j b%' ) and item.item_status_code <> '-' then 1 end) as "New JUV Non-Fiction Books other status 180",
count (case when item.record_creation_date_gmt > (now() - interval '12 months') and (itemcall.call_number_norm like 'j pbk' or itemcall.call_number_norm like 'j graphic%' or itemcall.call_number_norm like 'j fic%') and item.item_status_code <> '-' then 1 end) as "New Fiction Books other status 181",
count (case when item.record_creation_date_gmt > (now() - interval '12 months') and itemcall.call_number_norm like 'e%'  and item.item_status_code <> '-'  then 1 end) as "New E Books other status 182"


from
sierra_view.checkout as cout
right join sierra_view.item_view as item on item.id = cout.item_record_id 
inner join sierra_view.item_record_property as itemcall on itemcall.item_record_id = item.id
join sierra_view.bib_record_item_record_link as link on link.item_record_id = item.id
join sierra_view.phrase_entry as call on call.record_id = link.bib_record_id

where call.varfield_type_code = 'c' and item.location_code like 'gb%';
