
# -*- coding: utf-8 -*-
"""
Created on Thu Aug  2 14:32:38 2018

@author: nallen
"""


# This creates the count of all items at Byram Library, how many are checkedout and how many have other off shelf status... helps determine shelf space and popularity
#

import psycopg2
import xlsxwriter
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email.utils import formatdate
from email import encoders
from datetime import datetime



excelfile =  'ByramCount.xlsx' #name the spreadsheet (file) you are creating



#Set variables for email
emailhost = 'xxx.xxx.x.xx' #Update for your email host
emailport = '25' #Update for your port
emailsubject = 'ByramCount'
emailmessage = '''Attached is the total number of items in each collection, the number of items checked out in each collection and the total number of items off shelf.'''
emailfrom = 'nallen@greenwichlibrary.org' #this is your email. It means staff can hit reply and contact you with questions.
emailto = ['nallen@greenwichlibrary.org', 'kfuscaldo@greenwichlibrary.org', 'jgaither@greenwichlibrary.org'] #this is the list of people you want the email to go to.

try:
    conn = psycopg2.connect("dbname=iii user=sqlaccess host=sierra-db port=1032 password=PASSWORD sslmode=require") #update this information for your specific location
except psycopg2.Error as e:
    print ("Unable to connect to database: " + str(e))
    
cursor = conn.cursor()
cursor.execute(open("ByramCount.sql","r",).read()) #this is the list of people you want the email to go to.
rows = cursor.fetchall()
conn.close()


workbook = xlsxwriter.Workbook(excelfile, {'remove_timezone': True})



worksheet = workbook.add_worksheet('Byram')


worksheet.set_landscape()
worksheet.hide_gridlines(0)

#basic information that controls the display of your spreadsheet -ex. how dates are formated and whether anything is bolded-
percent_fmt = workbook.add_format({'num_format': '0.00%'})
eformat= workbook.add_format({'text_wrap': True, 'valign': 'top' , 'num_format': 'mm/dd/yy'})
eformatlabel= workbook.add_format({'text_wrap': True, 'valign': 'top', 'bold': True})


# sets the width of your columns (notice that in Python spreadsheets start with row and column 0

worksheet.set_column(0,0,29)
worksheet.set_column(1,1,10)
worksheet.set_column(2,2,16.86)
worksheet.set_column(3,3,16.86)
worksheet.set_column(4,4,16.86)
worksheet.set_column(5,5,16.86)

#Creates all the column & row headings
worksheet.write(0,0,'Collection', eformatlabel)
worksheet.write(0,1,'Total Count', eformatlabel)
worksheet.write(0,2,'Total Checked-Out', eformatlabel)
worksheet.write(0,3,'Percentage Checked-Out', eformatlabel)
worksheet.write(0,4,'No. w/ Status other than available', eformatlabel)
worksheet.write(0,5,'Percentage Not on Shelf', eformatlabel)
worksheet.write(1,0,'000-099', eformatlabel)
worksheet.write(2,0,'100-199', eformatlabel)
worksheet.write(3,0,'200-299', eformatlabel)
worksheet.write(4,0,'300-399', eformatlabel)
worksheet.write(5,0,'400-499', eformatlabel)
worksheet.write(6,0,'500-599', eformatlabel)
worksheet.write(7,0,'600-699', eformatlabel)
worksheet.write(8,0,'700-799', eformatlabel)
worksheet.write(9,0,'800-899', eformatlabel)
worksheet.write(10,0,'900-999', eformatlabel)
worksheet.write(11,0,'REF', eformatlabel)
worksheet.write(12,0,'Express', eformatlabel)
worksheet.write(13,0,'Fiction', eformatlabel)
worksheet.write(14,0,'Mystery', eformatlabel)
worksheet.write(15,0,'SciFi', eformatlabel)
worksheet.write(16,0,'Graphic Novel', eformatlabel)
worksheet.write(17,0,'LT', eformatlabel)
worksheet.write(18,0,'PBK', eformatlabel)
worksheet.write(19,0,'Japanese', eformatlabel)
worksheet.write(20,0,'Spanish', eformatlabel)
worksheet.write(21,0,'Language Learning', eformatlabel)
worksheet.write(22,0,'DVD', eformatlabel)
worksheet.write(23,0,'Music CDs', eformatlabel)
worksheet.write(24,0,'Audiobook', eformatlabel)
worksheet.write(25,0,'YA', eformatlabel)
worksheet.write(26,0,'Magazines (YA & Adult)', eformatlabel)
worksheet.write(27,0,'Music Scores', eformatlabel)
worksheet.write(28,0,'J Fiction', eformatlabel)
worksheet.write(29,0,'J Graphic Novels', eformatlabel)
worksheet.write(30,0,'E Books', eformatlabel)
worksheet.write(31,0,'E Boardbook', eformatlabel)
worksheet.write(32,0,'J Paperback', eformatlabel)
worksheet.write(33,0,'J Biography', eformatlabel)
worksheet.write(34,0,'J PIC', eformatlabel)
worksheet.write(35,0,'J-1,J-2,J-3', eformatlabel)##Added 2-5-24
worksheet.write(36,0,'J 000-099', eformatlabel)
worksheet.write(37,0,'J 100-199', eformatlabel)
worksheet.write(38,0,'J 200-299', eformatlabel)
worksheet.write(39,0,'J 300-399', eformatlabel)
worksheet.write(40,0,'J 400-499', eformatlabel)
worksheet.write(41,0,'J 500-599', eformatlabel)
worksheet.write(42,0,'J 600-699', eformatlabel)
worksheet.write(43,0,'J 700-799', eformatlabel)
worksheet.write(44,0,'J 800-899', eformatlabel)
worksheet.write(45,0,'J 900-999', eformatlabel)
worksheet.write(46,0,'J JPN', eformatlabel)
worksheet.write(47,0,'J SPA', eformatlabel)
worksheet.write(48,0,'J CHI', eformatlabel)
worksheet.write(49,0,'J FRE', eformatlabel)
worksheet.write(50,0,'J DVD', eformatlabel)
worksheet.write(51,0,'J Music CD', eformatlabel)
worksheet.write(52,0,'J Audiobook', eformatlabel)
worksheet.write(53,0,'E Audiobook', eformatlabel)
worksheet.write(54,0,'J Language Learning', eformatlabel)
worksheet.write(55,0,'J Magazine', eformatlabel)
worksheet.write(56,0,'J Reference', eformatlabel)
worksheet.write(57,0,'Total', eformatlabel)
worksheet.write(59,0,'New Books', eformatlabel)
worksheet.write(60,0,'New JUV Non-fiction Books', eformatlabel)
worksheet.write(61,0,'New JUV Fiction Books ', eformatlabel)
worksheet.write(62,0,'New JUV E Books', eformatlabel)


for rownum, col in enumerate(rows):
 # Checkout numbers the dgits in the brackets refer to order of the data returned by your SQL query
    worksheet.write(rownum+1,1,col[0])
    worksheet.write(rownum+2,1,col[1])
    worksheet.write(rownum+3,1,col[2])
    worksheet.write(rownum+4,1,col[3])
    worksheet.write(rownum+5,1,col[4])
    worksheet.write(rownum+6,1,col[5])
    worksheet.write(rownum+7,1,col[6])
    worksheet.write(rownum+8,1,col[7])
    worksheet.write(rownum+9,1,col[8]) 
    worksheet.write(rownum+10,1,col[9]) 
    worksheet.write(rownum+11,1,col[10])
    worksheet.write(rownum+12,1,col[11]) 
    worksheet.write(rownum+13,1,col[12])     
    worksheet.write(rownum+14,1,col[13])    
    worksheet.write(rownum+15,1,col[14])
    worksheet.write(rownum+16,1,col[15])
    worksheet.write(rownum+17,1,col[16])
    worksheet.write(rownum+18,1,col[17])
    worksheet.write(rownum+19,1,col[18]) 
    worksheet.write(rownum+20,1,col[19]) 
    worksheet.write(rownum+21,1,col[20])
    worksheet.write(rownum+22,1,col[21])
    worksheet.write(rownum+23,1,col[22])
    worksheet.write(rownum+24,1,col[23])
    worksheet.write(rownum+25,1,col[24])
    worksheet.write(rownum+26,1,col[25])
    worksheet.write(rownum+27,1,col[26])
    worksheet.write(rownum+28,1,col[27])
    worksheet.write(rownum+29,1,col[28]) 
    worksheet.write(rownum+30,1,col[29]) 
    worksheet.write(rownum+31,1,col[30])
    worksheet.write(rownum+32,1,col[31])
    worksheet.write(rownum+33,1,col[32])
    worksheet.write(rownum+34,1,col[33])
    worksheet.write(rownum+35,1,col[34])
    worksheet.write(rownum+36,1,col[35])
    worksheet.write(rownum+37,1,col[36])
    worksheet.write(rownum+38,1,col[37])
    worksheet.write(rownum+39,1,col[38]) 
    worksheet.write(rownum+40,1,col[39])
    worksheet.write(rownum+41,1,col[40])
    worksheet.write(rownum+42,1,col[41])
    worksheet.write(rownum+43,1,col[42])
    worksheet.write(rownum+44,1,col[43])
    worksheet.write(rownum+45,1,col[44])
    worksheet.write(rownum+46,1,col[45])
    worksheet.write(rownum+47,1,col[46])
    worksheet.write(rownum+48,1,col[47])
    worksheet.write(rownum+49,1,col[48]) 
    worksheet.write(rownum+50,1,col[49])
    worksheet.write(rownum+51,1,col[50])
    worksheet.write(rownum+52,1,col[51])
    worksheet.write(rownum+53,1,col[52])
    worksheet.write(rownum+54,1,col[53])
    worksheet.write(rownum+55,1,col[54]) 
    worksheet.write(rownum+56,1,col[55])
    worksheet.write(rownum+57,1,col[56])    
    worksheet.write(rownum+59,1,col[114])    
    worksheet.write(rownum+60,1,col[116])   
    worksheet.write(rownum+61,1,col[118])   
    worksheet.write(rownum+62,1,col[120])      
#CHECKEDOUT COLUMN    
    worksheet.write(rownum+1,2,col[57])
    worksheet.write(rownum+2,2,col[58])
    worksheet.write(rownum+3,2,col[59])
    worksheet.write(rownum+4,2,col[60])
    worksheet.write(rownum+5,2,col[61])
    worksheet.write(rownum+6,2,col[62])
    worksheet.write(rownum+7,2,col[63])
    worksheet.write(rownum+8,2,col[64])
    worksheet.write(rownum+9,2,col[65]) 
    worksheet.write(rownum+10,2,col[66]) 
    worksheet.write(rownum+11,2,col[67])
    worksheet.write(rownum+12,2,col[68]) 
    worksheet.write(rownum+13,2,col[69])     
    worksheet.write(rownum+14,2,col[70])
    worksheet.write(rownum+15,2,col[71])    
    worksheet.write(rownum+16,2,col[72])
    worksheet.write(rownum+17,2,col[73])
    worksheet.write(rownum+18,2,col[74])
    worksheet.write(rownum+19,2,col[75])
    worksheet.write(rownum+20,2,col[76]) 
    worksheet.write(rownum+21,2,col[77]) 
    worksheet.write(rownum+22,2,col[78])
    worksheet.write(rownum+23,2,col[79])
    worksheet.write(rownum+24,2,col[80])
    worksheet.write(rownum+25,2,col[81])
    worksheet.write(rownum+26,2,col[82])
    worksheet.write(rownum+27,2,col[83])
    worksheet.write(rownum+28,2,col[84])
    worksheet.write(rownum+29,2,col[85]) 
    worksheet.write(rownum+30,2,col[86]) 
    worksheet.write(rownum+31,2,col[87])
    worksheet.write(rownum+32,2,col[88])
    worksheet.write(rownum+33,2,col[89])
    worksheet.write(rownum+34,2,col[90])
    worksheet.write(rownum+35,2,col[91])
    worksheet.write(rownum+36,2,col[92])
    worksheet.write(rownum+37,2,col[93])
    worksheet.write(rownum+38,2,col[94])
    worksheet.write(rownum+39,2,col[95]) 
    worksheet.write(rownum+40,2,col[96])
    worksheet.write(rownum+41,2,col[97])
    worksheet.write(rownum+42,2,col[98])
    worksheet.write(rownum+43,2,col[99])
    worksheet.write(rownum+44,2,col[100])
    worksheet.write(rownum+45,2,col[101])
    worksheet.write(rownum+46,2,col[102])
    worksheet.write(rownum+47,2,col[103])
    worksheet.write(rownum+48,2,col[104])
    worksheet.write(rownum+49,2,col[105]) 
    worksheet.write(rownum+50,2,col[106])
    worksheet.write(rownum+51,2,col[107])
    worksheet.write(rownum+52,2,col[108])
    worksheet.write(rownum+53,2,col[109])
    worksheet.write(rownum+54,2,col[110])
    worksheet.write(rownum+55,2,col[111])
    worksheet.write(rownum+56,2,col[112])
    worksheet.write(rownum+57,2,col[113])    
    worksheet.write(rownum+59,2,col[115])
    worksheet.write(rownum+60,2,col[117])
    worksheet.write(rownum+61,2,col[119])
    worksheet.write(rownum+62,2,col[121])
    
    
#percentages checkedout
worksheet.write_formula('D2', "=C2/B2", percent_fmt)
worksheet.write_formula('D3', "=C3/B3", percent_fmt)
worksheet.write_formula('D4', "=C4/B4", percent_fmt)
worksheet.write_formula('D5', "=C5/B5", percent_fmt)
worksheet.write_formula('D6', "=C6/B6", percent_fmt)
worksheet.write_formula('D7', "=C7/B7", percent_fmt)
worksheet.write_formula('D8', "=C8/B8", percent_fmt)
worksheet.write_formula('D9', "=C9/B9", percent_fmt)
worksheet.write_formula('D10', "=C10/B10", percent_fmt)
worksheet.write_formula('D11', "=C11/B11", percent_fmt)
worksheet.write_formula('D12', "=C12/B12", percent_fmt)
worksheet.write_formula('D13', "=C13/B13", percent_fmt)
worksheet.write_formula('D14', "=C14/B14", percent_fmt)
worksheet.write_formula('D15', "=C15/B15", percent_fmt)
worksheet.write_formula('D16', "=C16/B16", percent_fmt)
worksheet.write_formula('D17', "=C17/B17", percent_fmt)
worksheet.write_formula('D18', "=C18/B18", percent_fmt)
worksheet.write_formula('D19', "=C19/B19", percent_fmt)
worksheet.write_formula('D20', "=C20/B20", percent_fmt)
worksheet.write_formula('D21', "=C21/B21", percent_fmt)
worksheet.write_formula('D22', "=C22/B22", percent_fmt)
worksheet.write_formula('D23', "=C23/B23", percent_fmt)
worksheet.write_formula('D24', "=C24/B24", percent_fmt)
worksheet.write_formula('D25', "=C25/B25", percent_fmt)
worksheet.write_formula('D26', "=C26/B26", percent_fmt)
worksheet.write_formula('D27', "=C27/B27", percent_fmt)
worksheet.write_formula('D28', "=C28/B28", percent_fmt)
worksheet.write_formula('D29', "=C29/B29", percent_fmt)
worksheet.write_formula('D30', "=C30/B30", percent_fmt)
worksheet.write_formula('D31', "=C31/B31", percent_fmt)
worksheet.write_formula('D32', "=C32/B32", percent_fmt)
worksheet.write_formula('D33', "=C33/B33", percent_fmt)
worksheet.write_formula('D34', "=C34/B34", percent_fmt)
worksheet.write_formula('D35', "=C35/B35", percent_fmt)
worksheet.write_formula('D36', "=C36/B36", percent_fmt)
worksheet.write_formula('D37', "=C37/B37", percent_fmt)
worksheet.write_formula('D38', "=C38/B38", percent_fmt)
worksheet.write_formula('D39', "=C39/B39", percent_fmt)
worksheet.write_formula('D40', "=C40/B40", percent_fmt)
worksheet.write_formula('D41', "=C41/B41", percent_fmt)
worksheet.write_formula('D42', "=C42/B42", percent_fmt)
worksheet.write_formula('D43', "=C43/B43", percent_fmt)
worksheet.write_formula('D44', "=C44/B44", percent_fmt)
worksheet.write_formula('D45', "=C45/B45", percent_fmt)
worksheet.write_formula('D46', "=C46/B46", percent_fmt)
worksheet.write_formula('D47', "=C47/B47", percent_fmt)
worksheet.write_formula('D48', "=C48/B48", percent_fmt)
worksheet.write_formula('D49', "=C49/B49", percent_fmt)
worksheet.write_formula('D50', "=C50/B50", percent_fmt)
worksheet.write_formula('D51', "=C51/B51", percent_fmt)
worksheet.write_formula('D52', "=C52/B52", percent_fmt)
worksheet.write_formula('D53', "=C53/B53", percent_fmt)
worksheet.write_formula('D54', "=C54/B54", percent_fmt)
worksheet.write_formula('D55', "=C55/B55", percent_fmt)
worksheet.write_formula('D56', "=C56/B56", percent_fmt)
worksheet.write_formula('D57', "=C57/B57", percent_fmt)
worksheet.write_formula('D58', "=C58/B58", percent_fmt)
worksheet.write_formula('D60', "=C60/B60", percent_fmt)
worksheet.write_formula('D61', "=C61/B61", percent_fmt)
worksheet.write_formula('D62', "=C62/B62", percent_fmt)
worksheet.write_formula('D63', "=C63/B63", percent_fmt)

#Items that are not available

worksheet.write(rownum+1,4,col[122])
worksheet.write(rownum+2,4,col[123])
worksheet.write(rownum+3,4,col[124])
worksheet.write(rownum+4,4,col[125])
worksheet.write(rownum+5,4,col[126])
worksheet.write(rownum+6,4,col[127])
worksheet.write(rownum+7,4,col[128])
worksheet.write(rownum+8,4,col[129])
worksheet.write(rownum+9,4,col[130]) 
worksheet.write(rownum+10,4,col[131]) 
worksheet.write(rownum+11,4,col[132])
worksheet.write(rownum+12,4,col[133]) 
worksheet.write(rownum+13,4,col[134]) 
worksheet.write(rownum+14,4,col[135])
worksheet.write(rownum+15,4,col[136])
worksheet.write(rownum+16,4,col[137])
worksheet.write(rownum+17,4,col[138])
worksheet.write(rownum+18,4,col[139])
worksheet.write(rownum+19,4,col[140])
worksheet.write(rownum+20,4,col[141]) 
worksheet.write(rownum+21,4,col[142]) 
worksheet.write(rownum+22,4,col[143])
worksheet.write(rownum+23,4,col[144])
worksheet.write(rownum+24,4,col[145])
worksheet.write(rownum+25,4,col[146])
worksheet.write(rownum+26,4,col[147])
worksheet.write(rownum+27,4,col[148])
worksheet.write(rownum+28,4,col[149])
worksheet.write(rownum+29,4,col[150]) 
worksheet.write(rownum+30,4,col[151]) 
worksheet.write(rownum+31,4,col[152])
worksheet.write(rownum+32,4,col[153])
worksheet.write(rownum+33,4,col[154])
worksheet.write(rownum+34,4,col[155])
worksheet.write(rownum+35,4,col[156])
worksheet.write(rownum+36,4,col[157])
worksheet.write(rownum+37,4,col[158])
worksheet.write(rownum+38,4,col[159])
worksheet.write(rownum+39,4,col[160]) 
worksheet.write(rownum+40,4,col[161])
worksheet.write(rownum+41,4,col[162])
worksheet.write(rownum+42,4,col[163])
worksheet.write(rownum+43,4,col[164])
worksheet.write(rownum+44,4,col[165])
worksheet.write(rownum+45,4,col[166])
worksheet.write(rownum+46,4,col[167])
worksheet.write(rownum+47,4,col[168])
worksheet.write(rownum+48,4,col[169])
worksheet.write(rownum+49,4,col[170]) 
worksheet.write(rownum+50,4,col[171])
worksheet.write(rownum+51,4,col[172])
worksheet.write(rownum+52,4,col[173])
worksheet.write(rownum+53,4,col[174])
worksheet.write(rownum+54,4,col[175])
worksheet.write(rownum+55,4,col[176])
worksheet.write(rownum+56,4,col[177])
worksheet.write(rownum+57,4,col[178])

worksheet.write(rownum+59,4,col[179])
worksheet.write(rownum+60,4,col[180])
worksheet.write(rownum+61,4,col[181])
worksheet.write(rownum+62,4,col[182])



#total percentage offshelf
worksheet.write_formula('F2', "=(C2+E2)/B2", percent_fmt)
worksheet.write_formula('F3', "=(C3+e3)/B3", percent_fmt)
worksheet.write_formula('F4', "=(C4+e4)/B4", percent_fmt)
worksheet.write_formula('F5', "=(C5+e5)/B5", percent_fmt)
worksheet.write_formula('F6', "=(C6+e6)/B6", percent_fmt)
worksheet.write_formula('F7', "=(C7+e7)/B7", percent_fmt)
worksheet.write_formula('F8', "=(C8+E8)/B8", percent_fmt)
worksheet.write_formula('F9', "=(C9+e9)/B9", percent_fmt)
worksheet.write_formula('F10', "=(C10+e10)/B10", percent_fmt)
worksheet.write_formula('F11', "=(C11+e11)/B11", percent_fmt)
worksheet.write_formula('F12', "=(C12+e12)/B12", percent_fmt)
worksheet.write_formula('F13', "=(C13+e13)/B13", percent_fmt)
worksheet.write_formula('F14', "=(C14+e14)/B14", percent_fmt)
worksheet.write_formula('F15', "=(C15+e15)/B15", percent_fmt)
worksheet.write_formula('F16', "=(C16+e16)/B16", percent_fmt)
worksheet.write_formula('F17', "=(C17+e17)/B17", percent_fmt)
worksheet.write_formula('F18', "=(C18+e18)/B18", percent_fmt)
worksheet.write_formula('F19', "=(C19+e19)/B19", percent_fmt)
worksheet.write_formula('F20', "=(C20+e20)/B20", percent_fmt)
worksheet.write_formula('F21', "=(C21+e21)/B21", percent_fmt)
worksheet.write_formula('F22', "=(C22+e22)/B22", percent_fmt)
worksheet.write_formula('F23', "=(C23+e23)/B23", percent_fmt)
worksheet.write_formula('F24', "=(C24+e24)/B24", percent_fmt)
worksheet.write_formula('F25', "=(C25+e25)/B25", percent_fmt)
worksheet.write_formula('F26', "=(C26+e26)/B26", percent_fmt)
worksheet.write_formula('F27', "=(C27+e27)/B27", percent_fmt)
worksheet.write_formula('F28', "=(C28+e28)/B28", percent_fmt)
worksheet.write_formula('F29', "=(C29+e29)/B29", percent_fmt)
worksheet.write_formula('F30', "=(C30+e30)/B30", percent_fmt)
worksheet.write_formula('F31', "=(C31+e31)/B31", percent_fmt)
worksheet.write_formula('F32', "=(C32+e32)/B32", percent_fmt)
worksheet.write_formula('F33', "=(C33+e33)/B33", percent_fmt)
worksheet.write_formula('F34', "=(C34+e34)/B34", percent_fmt)
worksheet.write_formula('F35', "=(C35+e35)/B35", percent_fmt)
worksheet.write_formula('F36', "=(C36+e36)/B36", percent_fmt)
worksheet.write_formula('F37', "=(C37+e37)/B37", percent_fmt)
worksheet.write_formula('F38', "=(C38+e38)/B38", percent_fmt)
worksheet.write_formula('F39', "=(C39+e39)/B39", percent_fmt)
worksheet.write_formula('F40', "=(C40+e40)/B40", percent_fmt)
worksheet.write_formula('F41', "=(C41+e41)/B41", percent_fmt)
worksheet.write_formula('F42', "=(C42+e42)/B42", percent_fmt)
worksheet.write_formula('F43', "=(C43+e43)/B43", percent_fmt)
worksheet.write_formula('F44', "=(C44+e44)/B44", percent_fmt)
worksheet.write_formula('F45', "=(C45+e45)/B45", percent_fmt)
worksheet.write_formula('F46', "=(C46+e46)/B46", percent_fmt)
worksheet.write_formula('F47', "=(C47+e47)/B47", percent_fmt)
worksheet.write_formula('F48', "=(C48+e48)/B48", percent_fmt)
worksheet.write_formula('F49', "=(C49+e49)/B49", percent_fmt)
worksheet.write_formula('F50', "=(C50+e50)/B50", percent_fmt)
worksheet.write_formula('F51', "=(C51+e51)/B51", percent_fmt)
worksheet.write_formula('F52', "=(C52+e52)/B52", percent_fmt)
worksheet.write_formula('F53', "=(C53+e53)/B53", percent_fmt)
worksheet.write_formula('F54', "=(C54+e54)/B54", percent_fmt)
worksheet.write_formula('F55', "=(C55+e55)/B55", percent_fmt)
worksheet.write_formula('F56', "=(C56+e56)/B56", percent_fmt)
worksheet.write_formula('F57', "=(C57+e57)/B57", percent_fmt)
worksheet.write_formula('F58', "=(C58+e58)/B58", percent_fmt)
worksheet.write_formula('F60', "=(C60+e60)/B60", percent_fmt)
worksheet.write_formula('F61', "=(C61+e61)/B61", percent_fmt)
worksheet.write_formula('F62', "=(C62+e62)/B62", percent_fmt)
worksheet.write_formula('F63', "=(C63+e63)/B63", percent_fmt)

workbook.close()


#Creating the email message
msg = MIMEMultipart()
msg['From'] = emailfrom
if type(emailto) is list:
    msg['To'] = ','.join(emailto)
else:
    msg['To'] = emailto
msg['Date'] = formatdate(localtime = True)
msg['Subject'] = emailsubject
msg.attach (MIMEText(emailmessage))
part = MIMEBase('application', "octet-stream")
part.set_payload(open(excelfile,"rb").read())
encoders.encode_base64(part)
part.add_header('Content-Disposition','attachment; filename=%s' % excelfile)
msg.attach(part)

#Sending the email message
smtp = smtplib.SMTP(emailhost, emailport)
smtp.sendmail(emailfrom, emailto, msg.as_string())
smtp.quit()








